spring:
  datasource:
    url: jdbc:mysql://localhost/event_store_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: 123456
  cloud:
    stream:
        kafka:
          binder:
            brokers: 127.0.0.1:9092
            zkNodes: 127.0.0.1:2181
        default-binder: kafka
    bus:
      enabled: true
  kafka:
    listener:
      concurrency: 3
    producer:
      batch-size: 1000
      retries: 0
      buffer-memory: 33554432
    bootstrap-servers: localhost:9092
choerodon:
  event:
    store:
        publish-msg-thread-num: 6
        query-status-thread-num: 4
hystrix:
  stream:
    queue:
      enabled: true
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
logging:
  level:
    com.netflix.discovery.DiscoveryClient: warn

